# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersBalance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='User_name',
            new_name='Currency',
        ),
        migrations.AddField(
            model_name='balance',
            name='Amount',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='im',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='UsersBalance.Balance'),
        ),
    ]
