# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersBalance', '0002_auto_20180108_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='im',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='Currency',
            new_name='Name',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
