# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersBalance', '0003_auto_20180108_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='Name',
            new_name='User_name',
        ),
    ]
