# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersBalance', '0004_auto_20180108_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='User_name',
            field=models.CharField(max_length=20),
        ),
    ]
