# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceWatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exchange_name', models.CharField(max_length=15)),
                ('Pair', models.CharField(max_length=15)),
            ],
        ),
    ]
