# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PriceWatch', '0002_exchanges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exchanges',
        ),
    ]
